question1=input("привіт! мене звати  Джарвіс, а тебе? :")
print(question1  + "! привіт як справи?")
print("я є штучний інтелект і мені навіть тижня нема, а тобі скільки років? ")
question2 = input (":")
print ("одже ти " + question1 + (" і тобі ") + question2 + " що ж приємно познайомитись")
print ("де ти мешкаєш?")
question3 = input (":")
print ("ОО! Круто! a я з Чернівців. давай порахуєм разом?")
calculator1 = float(input("введіть перше число :"))
calculator2 = float(input("введіть друге число :"))
a = (calculator1 + calculator2)
print ("+  " + str(a))
a = (calculator1 - calculator2)
print ("-  " + str(a))
a = (calculator1 * calculator2)
print ("*  " + str(a))
a = (calculator1 / calculator2)
print ("/  " + str(a))
a = (calculator1 % calculator2)
print ("%  " + str(a))
a = (calculator1 // calculator2)
print ("//  " + str(a))
a = (calculator1 ** calculator2)
print ("**  " + str(a))
